name: Build & Push MoonRay Base Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: moonray

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # ----------------------------
      # Checkout
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------
      # QEMU (for ARM64)
      # ----------------------------
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      # ----------------------------
      # Docker Buildx
      # ----------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ----------------------------
      # Login to Docker Hub
      # ----------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ----------------------------
      # Build & Push (multi-arch)
      # ----------------------------
      - name: Build and push BASE image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:base
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
      # ----------------------------
      # Build & Push ACL (multi-arch)
      # ----------------------------
      - name: Build and push ACL image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: acl.Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:acl
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Build and push CUDA image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: cuda.Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:cuda
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
